gui:
  theme:
    activeBorderColor:
      - "#957FB8" # oniViolet
      - bold
    inactiveBorderColor:
      - "#54546D" # sumiInk6
    optionsTextColor:
      - "#7AA89F" # waveAqua2
    selectedLineBgColor:
      - "#2D4F67" # waveBlue2
    selectedRangeBgColor:
      - "#2D4F67" # waveBlue2
    cherryPickedCommitBgColor:
      - "#98BB6C" # springGreen
    cherryPickedCommitFgColor:
      - "#1A1B2F" # bg (contrast on green)
    unstagedChangesColor:
      - "#C34043" # autumnRed
    defaultFgColor:
      - "#DCD7BA" # fujiWhite
git:
  paging:
    colorArg: always
    pager: delta --dark --syntax-theme "Kanagawa Wave" --paging=never
keybinding:
  universal:
    prevItem: 'k'
    nextItem: 'j'
    prevBlock: 'h'
    nextBlock: 'l'
